stephane_blog:
    resource: "@StephaneBlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# routes de mon blog
blog:
    resource: "@StephaneBlogBundle/Controller/"
    type:     annotation