services:
    stephane_blog.slugger:
        class: Stephane\BlogBundle\Service\Slugger
#        arguments: [@service_id, "plain_value", %parameter%]

    stephane_blog.article_listener:
        class: Stephane\BlogBundle\Service\SlugListener
        calls:
            - [setSlugger, ["@stephane_blog.slugger"]]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            